import forms from "@tailwindcss/forms";
import containerQueries from "@tailwindcss/container-queries";

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./*.html",
    "./admin/**/*.html",
    "./admin/**/*.js",
  ],
  theme: {
    extend: {
      colors: {
        tertiary: "#c7c7c7",
        "surface-container-low": "#1c1b1b",
        "on-error-container": "#ffdad6",
        "on-background": "#e5e2e1",
        "on-secondary-fixed": "#1c1b1b",
        "on-tertiary-container": "#3e4041",
        "tertiary-fixed": "#e2e2e2",
        "on-surface": "#e5e2e1",
        "primary-fixed-dim": "#e6c364",
        "secondary-fixed": "#e5e2e1",
        primary: "#e6c364",
        "on-primary-fixed-variant": "#584400",
        "on-secondary": "#313030",
        "on-surface-variant": "#d0c5b2",
        "outline-variant": "#4d4637",
        "surface-container-highest": "#353535",
        "secondary-fixed-dim": "#c9c6c5",
        "on-primary-fixed": "#241a00",
        "inverse-on-surface": "#313030",
        "on-tertiary-fixed": "#1a1c1c",
        "error-container": "#93000a",
        "inverse-surface": "#e5e2e1",
        "primary-container": "#c9a84c",
        "secondary-container": "#4a4949",
        "tertiary-fixed-dim": "#c6c6c7",
        "on-tertiary-fixed-variant": "#454747",
        "on-secondary-container": "#bab8b7",
        "on-error": "#690005",
        "inverse-primary": "#755b00",
        "surface-dim": "#131313",
        "tertiary-container": "#abacac",
        background: "#131313",
        "surface-container-lowest": "#0e0e0e",
        "on-primary-container": "#503d00",
        outline: "#99907e",
        error: "#ffb4ab",
        "primary-fixed": "#ffe08f",
        secondary: "#c9c6c5",
        "surface-container-high": "#2a2a2a",
        "on-primary": "#3d2e00",
        "on-tertiary": "#2f3131",
        "surface-container": "#20201f",
        surface: "#131313",
        "on-secondary-fixed-variant": "#474646",
        "surface-tint": "#e6c364",
        "surface-bright": "#393939",
        "surface-variant": "#353535",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "container-max": "1440px",
        "margin-mobile": "20px",
        unit: "8px",
        "margin-desktop": "64px",
        gutter: "24px",
      },
      fontFamily: {
        "body-lg": ["IBM Plex Sans Arabic", "sans-serif"],
        "display-lg-mobile": ["EB Garamond", "serif"],
        "display-lg": ["EB Garamond", "serif"],
        "headline-sm": ["EB Garamond", "serif"],
        "headline-md": ["EB Garamond", "serif"],
        "body-md": ["IBM Plex Sans Arabic", "sans-serif"],
        "label-md": ["IBM Plex Sans Arabic", "sans-serif"],
        "label-sm": ["IBM Plex Sans Arabic", "sans-serif"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "display-lg-mobile": ["36px", { lineHeight: "44px", fontWeight: "500" }],
        "display-lg": ["48px", { lineHeight: "60px", letterSpacing: "0", fontWeight: "500" }],
        "headline-sm": ["24px", { lineHeight: "32px", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "40px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
      },
    },
  },
  plugins: [forms, containerQueries],
};
